### ISSUE TITLE
Adding cplex solver

### ISSUE THREAD

**Issue by rraymondhp** [qiskit-community/prototype-qrao#23]
### What is the expected enhancement?
To be able to solve the same problem with CPLEX solver as provided by Qiskit here:
https://qiskit.org/documentation/optimization/stubs/qiskit_optimization.algorithms.CplexOptimizer.html

Having classical (CPLEX) solver will make it easier to compare the results.

**Comment by garrison** [comment]
Thanks for the suggestion, @rraymondhp.  @areeq-hasan has opened #27, which adds a demonstration of the `CplexOptimizer` to the first tutorial.  Is there anything else you had in mind as part of this issue?

**Comment by rraymondhp** [comment]
Hi Jim. This is exactly what I want. Thanks to @areeq-hasan for this.
