### ISSUE TITLE
Please link to GH Page in GitHub's About section

### ISSUE THREAD

**Issue by Eric-Arellano** [qiskit-community/prototype-qrao#55]
It is useful to have the link to the project docs on the GitHub home page for this repo. (Right now, it's currently the research paper, which would instead be better to be a link from the docs.)

To fix this, go to the "Code"/home page of the repo. Then click the wheel on the "about" section on the right. Set the website to your GitHub pages.

![Screenshot 2023-05-15 at 9 55 20 AM](https://github.com/Qiskit-Partners/qiskit-aqt-provider/assets/14852634/5085a3cd-e3d8-43e1-996f-be9e3c9d6147)

Thanks!

**Comment by garrison** [comment]
The Sphinx build, at https://qiskit-community.github.io/prototype-qrao/apidocs/index.html, contains the API References only.  The other modes of documentation -- tutorials, how-tos, and explanation -- are meant to be consumed on github.com.  Once this repository's contents have been migrated to qiskit-optimization (https://github.com/Qiskit/qiskit-optimization/pull/487), it will be archived, and I expect everything will be in the Sphinx build there.

**Comment by Eric-Arellano** [comment]
Ah, cool! Didn't realize this is being migrated.

I think it is still likely better to update the URL to https://qiskit-community.github.io/prototype-qrao/apidocs/index.html in the meantime. But I trust your judgment much more. Feel free to close this issue as "not planned"!

**Comment by garrison** [comment]
As before, I think this repository should be discontinued in favor of https://github.com/qiskit-community/qiskit-optimization/pull/487.  I had been planning to archive this repository once that pull request is merged, but I am not sure if/when that will happen.
